[package]
name = "server-biome-feature-spruce-trees-vanilla-mod"
version = "0.1.2"
edition = "2024"

[package.metadata.mod]
entry = "ServerBiomeFeatureSpruceTreesVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-biome-api", "block-spruce-log", "block-spruce-leaves"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
block-spruce-leaves = { path = "../block-spruce-leaves" }
block-spruce-log = { path = "../block-spruce-log" }
generated-block-registry = "0.1.0"
server-biome-api = { path = "../server-biome-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-biome-registry = { path = "../generated-biome-registry" }
generated-block-state = { path = "../generated-block-state" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
