[package]
name = "server-biome-feature-pale-oak-trees-vanilla-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ServerBiomeFeaturePaleOakTreesVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-biome-api", "block-pale-oak-log", "block-pale-oak-leaves", "block-resin-block"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
block-resin-block = { path = "../block-resin-block" }
block-pale-oak-leaves = { path = "../block-pale-oak-leaves" }
block-pale-oak-log = { path = "../block-pale-oak-log" }
generated-block-registry = "0.1.0"
server-biome-api = { path = "../server-biome-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-biome-registry = { path = "../generated-biome-registry" }
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
