[package]
name = "item-soul-sand-block"
version = "0.1.0"
edition = "2024"
[package.metadata.mod]
entry = "ItemSoulSandBlockMod"
[package.metadata.mod.dependencies]
init = ["block-soul-sand"]
run = []
ownership = []
[package.metadata.item]
id = "demo:soul_sand_block"
label = "Soul Sand"
[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-soul-sand = { path = "../block-soul-sand" }
tokio = { version = "1.48.0", features = ["full"] }
