[package]
name = "item-bamboo-mosaic-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemBambooMosaicBlockMod"

[package.metadata.mod.dependencies]
init = ["block-bamboo-mosaic"]
run = []
ownership = []

[package.metadata.item]
id = "demo:bamboo_mosaic_block"
label = "Bamboo Mosaic"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-bamboo-mosaic = { path = "../block-bamboo-mosaic" }
tokio = { version = "1.48.0", features = ["full"] }
