[package]
name = "client-player-scale-map-state-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerScaleMapStateMod"
provides = "client-player-scale-map-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
client-player-scale-map-api = { path = "../client-player-scale-map-api" }
tokio = { version = "1.48.0", features = ["full"] }
