[package]
name = "client-setting-input-i32-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientSettingInputI32Mod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "client-settings-input-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-menu-api = { path = "../client-menu-api" }
client-settings-input-api = { path = "../client-settings-input-api" }
tokio = { version = "1.48.0", features = ["full"] }
