[package]
name = "item-manager-generated-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "GeneratedItemManager"
provides = "item-manager-api"

[package.metadata.mod.dependencies]
init = ["item-registry-codegen"]
run = []
ownership = []

[dependencies]
generated-item-registry = "0.1.0"
item-api = { path = "../item-api" }
item-manager-api = { path = "../item-manager-api" }
item-render-api = { path = "../item-render-api" }
item-registry-codegen = { path = "../item-registry-codegen" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-item-registry = { path = "../generated-item-registry" }
