[package]
name = "client-player-render-blocky-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerRenderBlockyImpl"
provides = "client-player-render-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-camera-api",
    "client-player-gravity-map-api",
    "client-player-scale-map-api",
    "client-game-state-api",
    "network-protocol-mod",
    "blocky-model-api",
    "blocky-animation-api",
    "client-player-blocky-model-paths-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
blocky-animation-api = { git = "https://github.com/paolobettelini/modularis.git" }
blocky-model-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-camera-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-game-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-player-gravity-map-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-player-blocky-model-paths-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-player-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-player-scale-map-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
network-protocol-mod = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
