[package]
name = "item-red-nether-bricks-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemRedNetherBricksBlockMod"

[package.metadata.mod.dependencies]
init = ["block-red-nether-bricks"]
run = []
ownership = []

[package.metadata.item]
id = "demo:red_nether_bricks_block"
label = "Red Nether Bricks"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-red-nether-bricks = { path = "../block-red-nether-bricks" }
tokio = { version = "1.48.0", features = ["full"] }
