[package]
name = "item-magenta-terracotta-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemMagentaTerracottaBlockMod"

[package.metadata.mod.dependencies]
init = ["block-magenta-terracotta"]
run = []
ownership = []

[package.metadata.item]
id = "demo:magenta_terracotta_block"
label = "Magenta Terracotta"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-magenta-terracotta = { path = "../block-magenta-terracotta" }
tokio = { version = "1.48.0", features = ["full"] }
