[package]
name = "server-crafting-table-menu-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
audience-api = { git = "https://github.com/paolobettelini/modularis.git" }
cell-menu-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-block-registry = "0.1.0"
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { path = "../server-chunk-world-api" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
