[package]
name = "item-blackstone-block"
version = "0.1.0"
edition = "2024"
[package.metadata.mod]
entry = "ItemBlackstoneBlockMod"
[package.metadata.mod.dependencies]
init = ["block-blackstone"]
run = []
ownership = []
[package.metadata.item]
id = "demo:blackstone_block"
label = "Blackstone"
[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-blackstone = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
