[package]
name = "server-player-world-state-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerWorldStateMod"
provides = "server-player-world-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-player-registry-api",
    "server-player-lifecycle-events-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
