[package]
name = "client-player-sprint-jump-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerSprintJumpVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-player-controller-api",
    "player-jump-api",
    "client-camera-api",
    "player-gravity-api",
    "client-settings-api",
    "client-settings-registry-codegen",
    "client-game-state-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-camera-api = { path = "../client-camera-api" }
client-game-state-api = { path = "../client-game-state-api" }
client-keybinding-api = { path = "../client-keybinding-api" }
client-player-controller-api = { path = "../client-player-controller-api" }
client-settings-api = { path = "../client-settings-api" }
client-settings-registry-codegen = { path = "../client-settings-registry-codegen" }
generated-client-settings-registry = "0.1.0"
player-jump-api = { path = "../player-jump-api" }
player-gravity-api = { path = "../player-gravity-api" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-client-settings-registry = { path = "../generated-client-settings-registry" }
