[package]
name = "client-setting-chat-key"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientSettingChatKeyMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.setting]
id = "controls.chat_key"
label = "Chat key"
type = "string"
input = "keybinding"
default = "T"
section = "controls/keybinds"
section_label = "Keybinds"

[dependencies]
settings-schema-api = { path = "../settings-schema-api" }
tokio = { version = "1.48.0", features = ["full"] }
