[package]
name = "item-dead-tube-coral-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemDeadTubeCoralBlockMod"

[package.metadata.mod.dependencies]
init = ["block-dead-tube-coral-block"]
run = []
ownership = []

[package.metadata.item]
id = "demo:dead_tube_coral_block"
label = "Dead Tube Coral Block"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-dead-tube-coral-block = { path = "../block-dead-tube-coral-block" }
tokio = { version = "1.48.0", features = ["full"] }
