[package]
name = "item-red-concrete-powder-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemRedConcretePowderBlockMod"

[package.metadata.mod.dependencies]
init = ["block-red-concrete-powder"]
run = []
ownership = []

[package.metadata.item]
id = "demo:red_concrete_powder_block"
label = "Red Concrete Powder"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-red-concrete-powder = { path = "../block-red-concrete-powder" }
tokio = { version = "1.48.0", features = ["full"] }
