[package]
name = "client-player-controller-fps-bevy-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "FpsPlayerControllerBevyImpl"
provides = "client-player-controller-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-input-api",
    "client-camera-api",
    "collision-api",
    "player-gravity-api",
    "player-speed-api",
    "client-game-state-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-camera-api = { path = "../client-camera-api" }
collision-api = { path = "../collision-api" }
client-game-state-api = { path = "../client-game-state-api" }
client-input-api = { path = "../client-input-api" }
client-player-controller-api = { path = "../client-player-controller-api" }
player-gravity-api = { path = "../player-gravity-api" }
player-speed-api = { path = "../player-speed-api" }
tokio = { version = "1.48.0", features = ["full"] }
