[package]
name = "server-chunk-request-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerChunkRequestMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-network-events-api",
    "server-chunk-world-api",
    "server-player-registry-api",
    "server-chunk-residency-api",
    "network-protocol-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
chunk-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
network-protocol-mod = { path = "../network-protocol-mod" }
server-chunk-world-api = { path = "../server-chunk-world-api" }
server-chunk-residency-api = { path = "../server-chunk-residency-api" }
server-network-events-api = { path = "../server-network-events-api" }
server-player-registry-api = { path = "../server-player-registry-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
