[package]
name = "server-block-break-reach-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
block-edit-events-api = { path = "../block-edit-events-api" }
player-gravity-api = { path = "../player-gravity-api" }
server-block-interaction-rules-api = { path = "../server-block-interaction-rules-api" }
server-player-gravity-api = { path = "../server-player-gravity-api" }
server-player-hitbox-api = { path = "../server-player-hitbox-api" }
server-player-registry-api = { path = "../server-player-registry-api" }
