[package]
name = "server-block-break-reach-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
block-edit-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-block-interaction-rules-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
