[package]
name = "item-place-block-meta"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemPlaceBlockMetaMod"

[package.metadata.mod.dependencies]
init = ["block-registry-codegen"]
run = []
ownership = []

[package.metadata.item_metadata]
id = "demo:place_block"
field = "place_block"
type = "item_place_block_meta::PlaceBlock"

[dependencies]
block-registry-codegen = { git = "https://github.com/paolobettelini/modularis.git" }
generated-block-registry = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-block-registry = { path = "../generated-block-registry" }
