[package]
name = "client-kick-network-receive-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientKickNetworkReceiveMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-session-api",
    "client-game-state-api",
    "network-protocol-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-session-api = { path = "../client-session-api" }
generated-network-messages = "0.1.0"
network-protocol-mod = { path = "../network-protocol-mod" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
