[package]
name = "voxel-model-assets-fs-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "VoxelModelAssetsFsImpl"
provides = "voxel-model-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-model-api = { path = "../voxel-model-api" }
voxel-models-lib = { path = "../voxel-models-lib" }
