[package]
name = "player-jump-network-messages-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "PlayerJumpNetworkMessagesMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.network.messages]
clientbound = []
serverbound = ["player_jump_network_message_types::PlayerJumpRequest"]

[dependencies]
player-jump-network-message-types = { path = "../player-jump-network-message-types" }
tokio = { version = "1.48.0", features = ["full"] }
