[package]
name = "server-player-gravity-state-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerGravityStateMod"
provides = "server-player-gravity-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "player-gravity-api", "server-player-lifecycle-events-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
