[package]
name = "biome-tundra"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "BiomeTundraMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.biome]
id = "demo:tundra"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
