[package]
name = "client-player-sneak-edge-protection-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerSneakEdgeProtectionVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-game-state-api",
    "client-player-controller-api",
    "collision-api",
    "player-hitbox-api",
    "player-gravity-api",
    "player-sneak-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-player-controller-api = { path = "../client-player-controller-api" }
collision-api = { path = "../collision-api" }
player-gravity-api = { path = "../player-gravity-api" }
player-hitbox-api = { path = "../player-hitbox-api" }
player-sneak-api = { path = "../player-sneak-api" }
tokio = { version = "1.48.0", features = ["full"] }
