[package]
name = "server-crafting-table-menu-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerCraftingTableMenuVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "cell-menu-events-mod",
    "server-chunk-world-api",
]
run = []
ownership = []

[dependencies]
audience-api = { git = "https://github.com/paolobettelini/modularis.git" }
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
cell-menu-api = { git = "https://github.com/paolobettelini/modularis.git" }
cell-menu-events-mod = { path = "../cell-menu-events-mod" }
generated-block-registry = "0.1.0"
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { path = "../server-chunk-world-api" }
server-crafting-table-menu-lib = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-registry = { path = "../generated-block-registry" }
