[package]
name = "client-disconnect-menu-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientDisconnectMenuMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-session-api",
    "client-game-state-api",
    "client-ui-font-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-session-api = { path = "../client-session-api" }
client-ui-font-api = { path = "../client-ui-font-api" }
tokio = { version = "1.48.0", features = ["full"] }
