[package]
name = "server-player-name-unique-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerNameUniqueVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-player-registry-api"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
player-network-message-types = { path = "../player-network-message-types" }
server-player-admission-api = { path = "../server-player-admission-api" }
server-player-registry-api = { path = "../server-player-registry-api" }
server-player-name-unique-lib = { path = "../server-player-name-unique-lib" }
tokio = { version = "1.48.0", features = ["full"] }
