[package]
name = "block-manager-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
support = true

[dependencies]
block-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-block-registry = "0.1.0"

[patch.crates-io]
generated-block-registry = { path = "../generated-block-registry" }
