[package]
name = "server-network-udp-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerUdpNetwork"
provides = "server-network-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-config-api",
    "network-protocol-mod",
    "server-bevy-runner-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
generated-network-messages = "0.1.0"
network-protocol-mod = { path = "../network-protocol-mod" }
server-bevy-runner-mod = { path = "../server-bevy-runner-mod" }
server-config-api = { path = "../server-config-api" }
server-network-api = { path = "../server-network-api" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
