[package]
name = "chunk-api"
version = "0.1.1"
edition = "2024"

[dependencies]
block-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
chunk-section-api = { git = "https://github.com/paolobettelini/modularis.git" }
serde = { version = "1.0", features = ["derive"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-state = { path = "../generated-block-state" }
generated-block-registry = { path = "../generated-block-registry" }

[dev-dependencies]
serde_cbor = "0.11"
