name = "Modularis nether biomes"
version = "0.1.1"
description = "Modularis nether biomes."
modpacks = []
ignore = []
mods = [
    "biome-nether-wastes",
    "biome-soul-sand-valley",
    "biome-crimson-forest",
    "biome-warped-forest",
    "biome-basalt-deltas",
    "biome-sulfur-wastes",
    "biome-blackstone-ridges",
    "biome-cinnabar-grotto",
]
