name = "Minecraft demo Aether biome identities"
version = "0.0.1"
description = "Biome ID contributors for the Aether."
modpacks = []
ignore = []

mods = [
    "biome-aether-highlands",
    "biome-aether-golden-grove",
    "biome-aether-crystal-peaks",
]
