name = "Modularis overworld biomes"
version = "0.1.1"
description = "Modularis overworld biomes."
modpacks = []
ignore = []
mods = [
    "biome-plains",
    "biome-forest",
    "biome-birch-forest",
    "biome-desert",
    "biome-badlands",
    "biome-tundra",
    "biome-rocky-peaks",
    "biome-savanna",
    "biome-dark-forest",
    "biome-jungle",
    "biome-cherry-grove",
    "biome-mangrove-marsh",
    "biome-pale-garden",
    "biome-mushroom-fields",
    "biome-dripstone-karst",
]
