name = "Modularis biomes"
version = "0.1.1"
description = "Modularis vanilla biomes."
modpacks = ["blocks", "dimensions", "biomes-overworld", "biomes-nether", "biomes-aether"]
ignore = []
mods = ["biome-registry-codegen"]
