name = "Minecraft demo client"
description = "Multiplayer minecraft-style client using Bevy."
modpacks = ["common", "client-vanilla", "client-graphics"]
#ignore = ["client-sun-shadows-vanilla-mod"]
ignore = []
mods = [
    "client-config-default-impl",
    "client-log-filter-default-impl",
    "client-bevy-default-plugins-mod",
    "client-ui-font-dejavu-mod",
    "client-game-state-bevy-impl",
    "client-player-flight-state-mod",
    "client-player-flight-speed-state-mod",
    "client-player-speed-state-mod",
    "client-chat-state-mod",
    "client-dimension-state-mod",
    "client-sky-bevy-mod",
    "client-menu-bevy-impl",
    "client-main-menu-mod",
    "client-pause-menu-mod",
    "client-settings-input-registry-mod",
    "client-setting-input-string-mod",
    "client-setting-input-i32-mod",
    "client-setting-input-f32-mod",
    "client-setting-input-bool-mod",
    "client-setting-input-keybinding-mod",
    "client-setting-render-distance",
    "client-setting-mouse-sensitivity",
    "client-setting-fov",
    "client-setting-inventory-key",
    "client-setting-player-name",
    "client-player-name-random-default-mod",
    "client-setting-server-address",
    "client-settings-registry-codegen",
    "client-settings-bevy-menu-impl",
    "client-network-tcp-impl",
    "client-player-blocky-model-paths-mod",
    "client-blocky-model-bevy-render-mod",
    "client-blocky-animation-bevy-mod",
    "client-inventory-cache-mod",
    "client-inventory-optimistic-move-mod",
    "client-inventory-network-receive-mod",
    "client-inventory-network-send-mod",
    "client-inventory-ui-bevy-mod",
    "client-inventory-drag-drop-mod",
    "client-cell-menu-cache-mod",
    "client-cell-menu-optimistic-move-mod",
    "client-cell-menu-network-receive-mod",
    "client-cell-menu-network-send-mod",
    "client-cell-menu-ui-bevy-mod",
    "client-cell-menu-drag-drop-mod",
    "client-cell-menu-inventory-bridge-drag-drop-mod",
    "client-hotbar-ui-bevy-mod",
    "client-item-quantity-ui-mod",
    "client-item-favicon-ui-mod",
    "client-item-model-ui-mod",
    "client-session-network-mod",
    "client-kick-network-receive-mod",
    "client-disconnect-menu-mod",
    "client-chat-network-receive-mod",
    "client-chat-clear-network-receive-mod",
    "client-chat-network-send-mod",
    "client-chat-ui-bevy-mod",
    "client-player-flight-network-receive-mod",
    "client-player-flight-speed-network-receive-mod",
    "client-player-speed-network-receive-mod",
    "client-dimension-network-receive-mod",
    "client-sky-network-receive-mod",
    "client-portal-render-bevy-mod",
    "client-input-bevy-impl",
    "client-camera-first-person-bevy-impl",
    "client-block-interaction-events-mod",
    "client-block-edit-network-send-mod",
    "client-block-edit-network-receive-mod",
    "client-chunk-streaming-around-player-impl",
    "client-chunk-cache-network-impl",
    "client-collision-block-aabb-impl",
    "client-player-controller-fps-bevy-impl",
    "client-chunk-reset-on-dimension-change-mod",
    "client-player-dimension-position-mod",
    "client-player-spawn-mod",
    "client-block-interaction-raycast-mod",
    "client-chunk-vertex-lighting-pipeline-mod",
    "client-chunk-work-priority-mod",
    "client-voxel-model-assets-fs-impl",
    "client-chunk-mesh-voxel-models-impl",
    "client-chunk-request-network-mod",
    "client-chunk-render-bevy-impl",
    "client-player-render-blocky-impl",
    "client-player-network-sync-mod",
    "client-game-bootstrap-mod",
    "client-sun-state-mod",
    "client-sun-network-receive-mod",
    "client-sun-disc-bevy-mod",
    "client-block-outline-bevy-mod",
]
