name = "Minecraft demo items"
description = "Item contributors, item metadata contributors, and generated item registries."
modpacks = ["blocks"]
ignore = []

mods = [
    "item-dirt-block",
    "item-grass-block",
    "item-stone-block",
    "item-bedrock-block",
    "item-crafting-table-block",
    "item-diamond-block",
    "item-diamond-ore-block",
    "item-end-stone-block",
    "item-glowstone-block",
    "item-netherrack-block",
    "item-obsidian-block",
    "item-basalt-block",
    "item-birch-leaves-block",
    "item-birch-log-block",
    "item-blackstone-block",
    "item-cactus-block",
    "item-calcite-block",
    "item-crimson-nylium-block",
    "item-gravel-block",
    "item-moss-block",
    "item-oak-leaves-block",
    "item-oak-log-block",
    "item-packed-ice-block",
    "item-red-sand-block",
    "item-sand-block",
    "item-snow-block",
    "item-soul-sand-block",
    "item-soul-soil-block",
    "item-terracotta-block",
    "item-warped-nylium-block",
    "item-flint-and-steel",
    "item-quantity-meta",
    "item-place-block-meta",
    "item-favicon-meta",
    "item-portal-igniter-meta",
    "item-registry-codegen",
    "item-metadata-registry-codegen",
    "item-manager-generated-impl",
]
