name = "Minecraft demo network protocol"
version = "0.0.1"
description = "Common ECS event contracts, packet contributors, and the generated network protocol."
modpacks = ["blocks", "dimensions", "sounds"]
ignore = []

mods = [
    "inventory-events-mod",
    "cell-menu-events-mod",
    "hotbar-network-messages-mod",
    "block-edit-events-mod",
    "session-network-messages-mod",
    "kick-network-messages-mod",
    "player-network-messages-mod",
    "player-flight-network-messages-mod",
    "player-flight-speed-network-messages-mod",
    "player-speed-network-messages-mod",
    "player-scale-network-messages-mod",
    "chunk-network-messages-mod",
    "dimension-network-messages-mod",
    "world-context-network-messages-mod",
    "sky-network-messages-mod",
    "sun-network-messages-mod",
    "sound-network-messages-mod",
    "portal-network-messages-mod",
    "cell-menu-network-messages-mod",
    "chat-network-messages-mod",
    "chat-clear-network-messages-mod",
    "network-codegen-utils",
    "network-protocol-mod",
]
