name = "Modularis vanilla biomes"
version = "0.1.1"
description = "Modularis vanilla biomes."
modpacks = [
    "biomes",
    "server-biomes-overworld-vanilla",
    "server-biomes-nether-vanilla",
    "server-biomes-aether-vanilla",
]
ignore = []
mods = ["server-biome-climate-selector-vanilla-mod"]
