[package]
name = "item-orange-concrete-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemOrangeConcreteBlockMod"

[package.metadata.mod.dependencies]
init = ["block-orange-concrete"]
run = []
ownership = []

[package.metadata.item]
id = "demo:orange_concrete_block"
label = "Orange Concrete"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-orange-concrete = { path = "../block-orange-concrete" }
tokio = { version = "1.48.0", features = ["full"] }
