[package]
name = "server-command-clear-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerCommandClearVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-command-api", "server-chat-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chat-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-command-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
