[package]
name = "item-oxidized-chiseled-copper-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemOxidizedChiseledCopperBlockMod"

[package.metadata.mod.dependencies]
init = ["block-oxidized-chiseled-copper"]
run = []
ownership = []

[package.metadata.item]
id = "demo:oxidized_chiseled_copper_block"
label = "Oxidized Chiseled Copper"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-oxidized-chiseled-copper = { path = "../block-oxidized-chiseled-copper" }
tokio = { version = "1.48.0", features = ["full"] }
