[package]
name = "item-cobblestone-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemCobblestoneBlockMod"

[package.metadata.mod.dependencies]
init = ["block-cobblestone"]
run = []
ownership = []

[package.metadata.item]
id = "demo:cobblestone_block"
label = "Cobblestone"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-cobblestone = { path = "../block-cobblestone" }
tokio = { version = "1.48.0", features = ["full"] }
