[package]
name = "server-chunk-world-dynamic-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerChunkWorldDynamicImpl"
provides = "server-chunk-world-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-chunk-provider-registry-mod",
    "server-chunk-routing-api",
    "server-primary-chunk-provider-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
block-instance-api = { path = "../block-instance-api" }
chunk-api = { path = "../chunk-api" }
generated-block-registry = "0.1.0"
server-chunk-provider-api = { path = "../server-chunk-provider-api" }
server-chunk-provider-registry-mod = { path = "../server-chunk-provider-registry-mod" }
server-chunk-routing-api = { path = "../server-chunk-routing-api" }
server-chunk-world-api = { path = "../server-chunk-world-api" }
server-primary-chunk-provider-api = { path = "../server-primary-chunk-provider-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { path = "../voxel-math-api" }
world-instance-api = { path = "../world-instance-api" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
