[package]
name = "thecrown-main-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "TheCrownMainMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-scope-api",
    "server-scope-world-api",
    "server-chunk-world-api",
    "server-player-registry-api",
    "server-player-world-api",
    "server-player-lifecycle-events-mod",
    "server-chat-api",
    "server-sound-api",
    "block-edit-events-mod",
]
run = []
ownership = []

[dependencies]
actix-web = "4.13.0"
audience-api = { git = "https://github.com/paolobettelini/modularis.git" }
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
block-edit-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-events-mod = { path = "../block-edit-events-mod" }
block-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-block-registry = "0.1.0"
generated-sound-registry = "0.1.0"
leptos = { version = "0.8.20", default-features = false, features = ["ssr"] }
parkour-gameplay-lib = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chat-api = { path = "../server-chat-api" }
server-chunk-provider-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-routing-api = { path = "../server-chunk-routing-api" }
server-chunk-world-api = { path = "../server-chunk-world-api" }
server-player-chat-lib = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-mod = { path = "../server-player-lifecycle-events-mod" }
server-player-registry-api = { path = "../server-player-registry-api" }
server-player-world-api = { path = "../server-player-world-api" }
server-scope-api = { path = "../server-scope-api" }
server-scope-world-api = { path = "../server-scope-world-api" }
server-sound-api = { path = "../server-sound-api" }
tokio = { version = "1.48.0", features = ["full"] }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-sound-registry = { path = "../generated-sound-registry" }
