[package]
name = "server-sound-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
support = true

[dependencies]
audience-api = { path = "../audience-api" }
bevy = "0.17.3"
generated-sound-registry = "0.1.0"

[patch.crates-io]
generated-sound-registry = { path = "../generated-sound-registry" }

