[package]
name = "biome-soul-sand-valley"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "BiomeSoulSandValleyMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.biome]
id = "demo:soul-sand-valley"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
