[package]
name = "client-setting-grass-dynamic-wind"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientSettingGrassDynamicWindMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.setting]
id = "grass.dynamic_wind"
label = "Dynamic wind"
type = "bool"
input = "bool"
default = true
section = "graphics/grass"
section_label = "Grass"

[dependencies]
settings-schema-api = { path = "../settings-schema-api" }
tokio = { version = "1.48.0", features = ["full"] }
