[package]
name = "server-block-break-reach-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerBlockBreakReachVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "block-edit-events-mod",
    "server-player-gravity-api",
    "server-player-hitbox-api",
    "server-block-interaction-rules-api",
    "server-player-registry-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-block-interaction-rules-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-block-break-reach-lib = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
