[package]
name = "server-dimension-overworld-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerDimensionOverworldMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-dimension-api", "dimension-overworld"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
dimension-overworld = { path = "../dimension-overworld" }
generated-dimension-registry = "0.1.0"
server-chunk-provider-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-dimension-api = { path = "../server-dimension-api" }
tokio = { version = "1.48.0", features = ["full"] }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-dimension-registry = { path = "../generated-dimension-registry" }
