[package]
name = "server-voxel-frame-persistence-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ServerVoxelFramePersistenceMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod","server-chunk-world-api","server-world-catalog-api","server-world-data-storage-api","server-voxel-frame-events-mod"]
run = []
ownership = []

[dependencies]
server-voxel-frame-events-mod = { path = "../server-voxel-frame-events-mod" }
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
server-chunk-world-api = { path = "../server-chunk-world-api" }
server-world-catalog-api = { path = "../server-world-catalog-api" }
server-world-data-storage-api = { path = "../server-world-data-storage-api" }
voxel-frame-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-frame-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-frame-storage-lib = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
