[package]
name = "block-birch-leaves"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "BlockBirchLeavesMod"

[package.metadata.mod.dependencies]
init = ["voxel-model-block-templates-mod"]
run = []
ownership = []

[package.metadata.block]
id = "demo:birch-leaves"

[dependencies]
block-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-model-block-templates-mod = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
