[package]
name = "client-chunk-reset-on-world-change-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientChunkResetOnWorldChangeMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-world-context-api",
    "client-chunk-cache-api",
    "client-chunk-streaming-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
client-chunk-cache-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-chunk-streaming-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-world-context-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
