[package]
name = "client-chunk-render-bevy-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ChunkRenderBevyImpl"
provides = "client-chunk-render-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-chunk-cache-api",
    "client-chunk-streaming-api",
    "client-chunk-mesh-api",
    "block-manager-api",
    "client-game-state-api",
    "client-chunk-work-priority-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
block-manager-api = { path = "../block-manager-api" }
client-chunk-mesh-api = { path = "../client-chunk-mesh-api" }
client-chunk-cache-api = { path = "../client-chunk-cache-api" }
client-chunk-render-api = { path = "../client-chunk-render-api" }
client-chunk-streaming-api = { path = "../client-chunk-streaming-api" }
client-game-state-api = { path = "../client-game-state-api" }
client-chunk-work-priority-api = { path = "../client-chunk-work-priority-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { path = "../voxel-math-api" }
