[package]
name = "block-manager-registry-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "RegistryBlockManager"
provides = "block-manager-api"

[package.metadata.mod.dependencies]
init = ["block-registry-codegen"]
run = []
ownership = []

[dependencies]
block-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-manager-api = { path = "../block-manager-api" }
block-registry-codegen = { path = "../block-registry-codegen" }
block-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-block-registry = "0.1.0"
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-block-registry = { path = "../generated-block-registry" }
