[package]
name = "item-nether-quartz-ore-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemNetherQuartzOreBlockMod"

[package.metadata.mod.dependencies]
init = ["block-nether-quartz-ore"]
run = []
ownership = []

[package.metadata.item]
id = "demo:nether_quartz_ore_block"
label = "Nether Quartz Ore"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-nether-quartz-ore = { path = "../block-nether-quartz-ore" }
tokio = { version = "1.48.0", features = ["full"] }
