[package]
name = "client-chunk-face-shading-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientChunkFaceShadingVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "client-chunk-vertex-lighting-api"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
block-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-chunk-vertex-lighting-api = { path = "../client-chunk-vertex-lighting-api" }
tokio = { version = "1.48.0", features = ["full"] }

