[package]
name = "external-link-network-messages-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ExternalLinkNetworkMessagesMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.network.messages]
clientbound = ["external_link_network_message_types::ShowExternalLink"]
serverbound = []

[dependencies]
external-link-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
