[package]
name = "cell-menu-api"
version = "0.1.0"
edition = "2024"

[dependencies]
audience-api = { git = "https://github.com/paolobettelini/modularis.git" }
bevy = "0.17.3"
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
serde = { version = "1.0", features = ["derive"] }
