[package]
name = "client-chunk-streaming-around-player-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "AroundPlayerChunkStreaming"
provides = "client-chunk-streaming-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-settings-api",
    "client-camera-api",
    "client-game-state-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
client-camera-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-chunk-streaming-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-game-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-client-settings-registry = "0.1.0"
client-settings-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-client-settings-registry = { path = "../generated-client-settings-registry" }
