[package]
name = "client-chunk-mesh-voxel-models-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "VoxelModelChunkMesher"
provides = "client-chunk-mesh-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "block-manager-api",
    "client-chunk-vertex-lighting-api",
    "voxel-model-api",
]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
block-manager-api = { path = "../block-manager-api" }
block-render-api = { path = "../block-render-api" }
client-chunk-mesh-api = { path = "../client-chunk-mesh-api" }
client-chunk-vertex-lighting-api = { path = "../client-chunk-vertex-lighting-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { path = "../voxel-math-api" }
voxel-model-api = { path = "../voxel-model-api" }
voxel-models-lib = { path = "../voxel-models-lib" }
