[package]
name = "item-blue-concrete-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemBlueConcreteBlockMod"

[package.metadata.mod.dependencies]
init = ["block-blue-concrete"]
run = []
ownership = []

[package.metadata.item]
id = "demo:blue_concrete_block"
label = "Blue Concrete"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-blue-concrete = { path = "../block-blue-concrete" }
tokio = { version = "1.48.0", features = ["full"] }
