[package]
name = "server-block-interaction-rules-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerBlockInteractionRulesVanillaMod"
provides = "server-block-interaction-rules-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
server-block-interaction-rules-api = { path = "../server-block-interaction-rules-api" }
tokio = { version = "1.48.0", features = ["full"] }
