[package]
name = "player-hitbox-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
support = true

[dependencies]
bevy = "0.17.3"
block-shape-api = { git = "https://github.com/paolobettelini/modularis.git" }
collision-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
