[package]
name = "client-hotbar-scroll-input-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientHotbarScrollInputMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-game-state-api",
    "client-inventory-cache-api",
    "inventory-events-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-inventory-cache-api = { path = "../client-inventory-cache-api" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-mod = { path = "../inventory-events-mod" }
tokio = { version = "1.48.0", features = ["full"] }
