[package]
name = "item-terracotta-block"
version = "0.1.0"
edition = "2024"
[package.metadata.mod]
entry = "ItemTerracottaBlockMod"
[package.metadata.mod.dependencies]
init = ["block-terracotta"]
run = []
ownership = []
[package.metadata.item]
id = "demo:terracotta_block"
label = "Terracotta"
[dependencies]
item-api = { path = "../item-api" }
item-render-api = { path = "../item-render-api" }
block-terracotta = { path = "../block-terracotta" }
tokio = { version = "1.48.0", features = ["full"] }
