[package]
name = "server-patchwork-auth-handshake-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPatchworkAuthHandshakeMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-network-api",
    "network-protocol-mod",
    "network-frame-security-state-mod",
    "network-transport-events-mod",
    "patchwork-game-auth-events-mod",
    "server-patchwork-auth-instance-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
generated-network-messages = "0.1.0"
network-frame-security-api = { path = "../network-frame-security-api" }
network-frame-security-state-mod = { path = "../network-frame-security-state-mod" }
network-protocol-mod = { path = "../network-protocol-mod" }
network-transport-events-mod = { path = "../network-transport-events-mod" }
patchwork-auth-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
patchwork-game-auth-api = { path = "../patchwork-game-auth-api" }
patchwork-game-auth-crypto-lib = { git = "https://github.com/paolobettelini/modularis.git" }
patchwork-game-auth-events-mod = { path = "../patchwork-game-auth-events-mod" }
patchwork-game-auth-http-lib = { git = "https://github.com/paolobettelini/modularis.git" }
server-network-api = { path = "../server-network-api" }
server-patchwork-auth-instance-mod = { path = "../server-patchwork-auth-instance-mod" }
tokio = { version = "1.48.0", features = ["full"] }
uuid = { version = "1", features = ["v4"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
