[package]
name = "item-anvil-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemAnvilBlockMod"

[package.metadata.mod.dependencies]
init = ["block-anvil"]
run = []
ownership = []

[package.metadata.item]
id = "demo:anvil_block"
label = "Anvil"

[dependencies]
block-anvil = { git = "https://github.com/paolobettelini/modularis.git" }
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
