[package]
name = "server-dimension-aether-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerDimensionAetherMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-dimension-api",
    "server-chunk-provider-aether-mod",
    "dimension-aether",
]
run = []
ownership = []

[dependencies]
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
dimension-aether = { git = "https://github.com/paolobettelini/modularis.git" }
generated-dimension-registry = "0.1.0"
server-chunk-provider-aether-mod = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-provider-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-dimension-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-dimension-registry = { path = "../generated-dimension-registry" }
