[package]
name = "item-redstone-ore-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemRedstoneOreBlockMod"

[package.metadata.mod.dependencies]
init = ["block-redstone-ore"]
run = []
ownership = []

[package.metadata.item]
id = "demo:redstone_ore_block"
label = "Redstone Ore"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-redstone-ore = { path = "../block-redstone-ore" }
tokio = { version = "1.48.0", features = ["full"] }
