[package]
name = "client-block-break-overlay-bevy-mod"
version = "0.1.2"
edition = "2024"

[package.metadata.mod]
entry = "ClientBlockBreakOverlayBevyMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod", "client-bevy-default-plugins-mod", "client-block-damage-api",
    "client-chunk-cache-api", "block-shape-api", "client-game-state-api",
]
run = []
ownership = []

[dependencies]
client-voxel-frame-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-frame-api = { git = "https://github.com/paolobettelini/modularis.git" }
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
block-shape-api = { path = "../block-shape-api" }
client-bevy-default-plugins-mod = { path = "../client-bevy-default-plugins-mod" }
client-block-damage-api = { path = "../client-block-damage-api" }
client-chunk-cache-api = { path = "../client-chunk-cache-api" }
client-game-state-api = { path = "../client-game-state-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
