[package]
name = "server-inventory-default-loadout-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
block-manager-api = { path = "../block-manager-api" }
generated-item-metadata = "0.1.0"
inventory-core-api = { path = "../inventory-core-api" }
inventory-events-api = { path = "../inventory-events-api" }
item-instance-api = { path = "../item-instance-api" }
item-manager-api = { path = "../item-manager-api" }
item-place-block-meta = { path = "../item-place-block-meta" }
item-portal-igniter-meta = { path = "../item-portal-igniter-meta" }
item-quantity-meta = { path = "../item-quantity-meta" }
server-inventory-layout-api = { path = "../server-inventory-layout-api" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-item-metadata = { path = "../generated-item-metadata" }
generated-item-registry = { path = "../generated-item-registry" }
