[package]
name = "server-inventory-default-loadout-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
block-manager-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-item-metadata = "0.1.0"
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-manager-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-place-block-meta = { git = "https://github.com/paolobettelini/modularis.git" }
item-portal-igniter-meta = { git = "https://github.com/paolobettelini/modularis.git" }
item-quantity-meta = { git = "https://github.com/paolobettelini/modularis.git" }
server-inventory-layout-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-item-metadata = { path = "../generated-item-metadata" }
generated-item-registry = { path = "../generated-item-registry" }
