[package]
name = "client-player-scale-state-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerScaleStateMod"
provides = "player-scale-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
player-scale-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
