[package]
name = "client-cell-menu-optimistic-move-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientCellMenuOptimisticMoveMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "cell-menu-events-mod",
    "client-cell-menu-cache-api",
    "client-inventory-cache-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
cell-menu-api = { path = "../cell-menu-api" }
cell-menu-events-mod = { path = "../cell-menu-events-mod" }
client-cell-menu-cache-api = { path = "../client-cell-menu-cache-api" }
client-inventory-cache-api = { path = "../client-inventory-cache-api" }
inventory-core-api = { path = "../inventory-core-api" }
tokio = { version = "1.48.0", features = ["full"] }
