[package]
name = "client-player-sneak-input-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerSneakInputVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-game-state-api",
    "player-sneak-api",
    "client-settings-api",
    "client-settings-registry-codegen",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-keybinding-api = { path = "../client-keybinding-api" }
client-settings-api = { path = "../client-settings-api" }
client-settings-registry-codegen = { path = "../client-settings-registry-codegen" }
generated-client-settings-registry = "0.1.0"
player-sneak-api = { path = "../player-sneak-api" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-client-settings-registry = { path = "../generated-client-settings-registry" }
