[package]
name = "server-player-gravity-network-sync-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerGravityNetworkSyncMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-network-events-api",
    "server-player-lifecycle-events-mod",
    "server-player-gravity-api",
    "server-player-registry-api",
    "server-player-visibility-api",
    "network-protocol-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
player-gravity-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
network-protocol-mod = { git = "https://github.com/paolobettelini/modularis.git" }
server-network-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-lifecycle-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-visibility-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
