[package]
name = "client-grass-mesh-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
api = true

[dependencies]
bevy = "0.17.3"
chunk-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-dimension-api = { path = "../client-dimension-api" }
client-grass-settings-api = { path = "../client-grass-settings-api" }
