[package]
name = "server-player-visibility-all-impl"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerVisibilityAllImpl"
provides = "server-player-visibility-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
server-player-visibility-api = { path = "../server-player-visibility-api" }
tokio = { version = "1.48.0", features = ["full"] }

