[package]
name = "server-cell-menu-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
support = true

[dependencies]
audience-api = { git = "https://github.com/paolobettelini/modularis.git" }
bevy = "0.17.3"
cell-menu-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
