[package]
name = "client-external-link-events-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ClientExternalLinkEventsMod"
provides = "client-external-link-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-external-link-api = { path = "../client-external-link-api" }
tokio = { version = "1.48.0", features = ["full"] }
