[package]
name = "item-cobbled-deepslate-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemCobbledDeepslateBlockMod"

[package.metadata.mod.dependencies]
init = ["block-cobbled-deepslate"]
run = []
ownership = []

[package.metadata.item]
id = "demo:cobbled_deepslate_block"
label = "Cobbled Deepslate"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-cobbled-deepslate = { path = "../block-cobbled-deepslate" }
tokio = { version = "1.48.0", features = ["full"] }
