[package]
name = "client-voxel-frame-movement-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ClientVoxelFrameMovementMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path="../bevy-mod" }
client-voxel-frame-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-voxel-frame-movement-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = {version="1",features=["full"]}
