[package]
name = "server-biome-feature-bamboo-groves-vanilla-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ServerBiomeFeatureBambooGrovesVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-biome-api", "block-bamboo-block", "block-stripped-bamboo-block", "block-bamboo-mosaic"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
block-bamboo-mosaic = { path = "../block-bamboo-mosaic" }
block-stripped-bamboo-block = { path = "../block-stripped-bamboo-block" }
block-bamboo-block = { path = "../block-bamboo-block" }
generated-block-registry = "0.1.0"
server-biome-api = { path = "../server-biome-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-biome-registry = { path = "../generated-biome-registry" }
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
