[package]
name = "client-player-sneak-camera-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerSneakCameraVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-game-state-api",
    "client-camera-api",
    "client-player-controller-api",
    "player-gravity-api",
    "player-scale-api",
    "player-sneak-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
client-camera-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-game-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-player-controller-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-scale-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-sneak-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
