[package]
name = "server-dimension-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
api = true

[dependencies]
bevy = "0.17.3"
generated-dimension-registry = "0.1.0"
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-provider-api = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-dimension-registry = { path = "../generated-dimension-registry" }
