[package]
name = "cell-menu-network-message-types"
version = "0.1.0"
edition = "2024"

[dependencies]
cell-menu-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
serde = { version = "1.0", features = ["derive"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
