[package]
name = "item-mangrove-planks-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemMangrovePlanksBlockMod"

[package.metadata.mod.dependencies]
init = ["block-mangrove-planks"]
run = []
ownership = []

[package.metadata.item]
id = "demo:mangrove_planks_block"
label = "Mangrove Planks"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-mangrove-planks = { path = "../block-mangrove-planks" }
tokio = { version = "1.48.0", features = ["full"] }
