#!/usr/bin/env bash
set -euo pipefail

# This script replaces all local dependencies with the respect remote GitHub dependency,
# but overrides the dependency locally using config.toml.
# Put this file in mods/.cargo/.
# It works regardless of whether it is launched from mods/ or mods/.cargo/.

# Example
#
# [dependencies]
# foo = { path = "../foo" }
# bar = { path = "../bar", features = ["abc"] }
#
# turns into
#
# [dependencies]
# foo = { git = "https://github.com/paolobettelini/modularis.git" }
# bar = { git = "https://github.com/paolobettelini/modularis.git", features = ["abc"] }
#
# but the config.toml still overrides the dependencies with the local ones.

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
mods_dir="$(dirname -- "$script_dir")"
config_path="$script_dir/config.toml"
repo_url="https://github.com/paolobettelini/modularis.git"

dry_run=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) dry_run=1 ;;
        *)
            echo "usage: $(basename -- "$0") [--dry-run]" >&2
            exit 2
            ;;
    esac
done

for cmd in perl awk mktemp cmp diff; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "error: $cmd is required" >&2
        exit 1
    fi
done

shopt -s nullglob
manifests=("$mods_dir"/*/Cargo.toml)
shopt -u nullglob

if ((${#manifests[@]} == 0)); then
    echo "error: no Cargo.toml found directly under $mods_dir" >&2
    exit 1
fi

config_tmp="$(mktemp)"
cleanup() {
    rm -f -- "$config_tmp"
}
trap cleanup EXIT

# Build config.toml first. Package names come from [package].name; paths are
# relative to mods/ because config.toml lives in mods/.cargo/.
printf '%s\n' '# Generated by .cargo/sync-modularis-deps.sh. Do not edit by hand.' > "$config_tmp"
printf '[patch."%s"]\n' "$repo_url" >> "$config_tmp"

crate_count=0
for manifest in "${manifests[@]}"; do
    crate_dir="$(dirname -- "$manifest")"
    folder="$(basename -- "$crate_dir")"

    package_name="$(awk '
        BEGIN { in_package = 0 }
        /^[[:space:]]*\[package\][[:space:]]*(#.*)?$/ {
            in_package = 1
            next
        }
        /^[[:space:]]*\[/ {
            if (in_package) exit
        }
        in_package && /^[[:space:]]*name[[:space:]]*=/ {
            line = $0
            sub(/^[[:space:]]*name[[:space:]]*=[[:space:]]*/, "", line)
            sub(/[[:space:]]*#.*/, "", line)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)

            quote = substr(line, 1, 1)
            if (quote == "\"" || quote == sprintf("%c", 39)) {
                line = substr(line, 2)
                pos = index(line, quote)
                if (pos > 0) line = substr(line, 1, pos - 1)
            }

            print line
            exit
        }
    ' "$manifest")"

    if [[ -z "$package_name" ]]; then
        echo "warning: cannot find [package].name in $manifest; skipping it" >&2
        continue
    fi

    if [[ "$folder" == *'"'* ]]; then
        echo "error: unsupported double quote in crate folder name: $folder" >&2
        exit 1
    fi

    printf '%s = { path = "%s" }\n' "$package_name" "$folder" >> "$config_tmp"
    ((crate_count += 1))
done

# Rewrites only sibling path dependencies such as ../foo where
# mods/foo/Cargo.toml exists. Supports inline tables and
# [dependencies.foo]-style subtables, including dev/build/target/workspace deps.
export MODS_DIR="$mods_dir"
export REPO_URL="$repo_url"

read -r -d '' perl_program <<'PERL' || true
BEGIN {
    $in_dep_table = 0;
    $in_dep_subtable = 0;
}

if (/^\s*\[([^\]]+)\]\s*(?:#.*)?$/) {
    my $section = $1;

    $in_dep_table = (
        $section =~ /^(?:dependencies|dev-dependencies|build-dependencies|workspace\.dependencies)$/
        || $section =~ /^target\..*\.(?:dependencies|dev-dependencies|build-dependencies)$/
    );

    $in_dep_subtable = (
        $section =~ /^(?:dependencies|dev-dependencies|build-dependencies)\./
        || $section =~ /^workspace\.dependencies\./
        || $section =~ /^target\..*\.(?:dependencies|dev-dependencies|build-dependencies)\./
    );
}

if ($in_dep_table) {
    if (/\bpath\s*=\s*(["\x27])\.\.\/([^\/"\x27]+)\/?\1/) {
        my $folder = $2;
        if (-f "$ENV{MODS_DIR}/$folder/Cargo.toml") {
            s/\bpath\s*=\s*(["\x27])\.\.\/\Q$folder\E\/?\1/git = "$ENV{REPO_URL}"/;
        }
    }
}
elsif ($in_dep_subtable) {
    if (/^\s*path\s*=\s*(["\x27])\.\.\/([^\/"\x27]+)\/?\1/) {
        my $folder = $2;
        if (-f "$ENV{MODS_DIR}/$folder/Cargo.toml") {
            s/^(\s*)path(\s*=\s*)(["\x27])\.\.\/\Q$folder\E\/?\3/$1git$2"$ENV{REPO_URL}"/;
        }
    }
}
PERL

changed_files=0
for manifest in "${manifests[@]}"; do
    candidate="$(mktemp)"

    if ! perl -pe "$perl_program" "$manifest" > "$candidate"; then
        echo "error: failed to process $manifest" >&2
        rm -f -- "$candidate"
        exit 1
    fi

    if ! cmp -s -- "$manifest" "$candidate"; then
        ((changed_files += 1))

        if ((dry_run)); then
            echo
            diff -u -- "$manifest" "$candidate" || true
        else
            cat -- "$candidate" > "$manifest"
        fi
    fi

    rm -f -- "$candidate"
done

if ((dry_run)); then
    if [[ -f "$config_path" ]]; then
        if ! cmp -s -- "$config_path" "$config_tmp"; then
            echo
            diff -u -- "$config_path" "$config_tmp" || true
        fi
    else
        echo
        echo "--- $config_path (new)"
        cat -- "$config_tmp"
    fi
else
    cat -- "$config_tmp" > "$config_path"
fi

echo
if ((dry_run)); then
    echo "dry-run: $changed_files Cargo.toml file(s) would change"
    echo "dry-run: config.toml would contain $crate_count local crate patch(es)"
else
    echo "rewritten: $changed_files Cargo.toml file(s)"
    echo "generated: $config_path ($crate_count local crate patch(es))"
fi