[package]
name = "server-block-placement-api"
version = "0.1.1"
edition = "2024"

[dependencies]
bevy = "0.17.3"
block-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-frame-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
