[package]
name = "item-warped-nylium-block"
version = "0.1.0"
edition = "2024"
[package.metadata.mod]
entry = "ItemWarpedNyliumBlockMod"
[package.metadata.mod.dependencies]
init = ["block-warped-nylium"]
run = []
ownership = []
[package.metadata.item]
id = "demo:warped_nylium_block"
label = "Warped Nylium"
[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-warped-nylium = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
