[package]
name = "server-world-catalog-build-server-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerWorldCatalogBuildServerImpl"
provides = "server-world-catalog-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "dimension-overworld",
    "dimension-nether",
    "dimension-aether",
]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
dimension-aether = { path = "../dimension-aether" }
dimension-nether = { path = "../dimension-nether" }
dimension-overworld = { path = "../dimension-overworld" }
generated-dimension-registry = "0.1.0"
server-world-catalog-api = { path = "../server-world-catalog-api" }
tokio = { version = "1.48.0", features = ["full"] }
world-instance-api = { path = "../world-instance-api" }

[patch.crates-io]
generated-dimension-registry = { path = "../generated-dimension-registry" }
