[package]
name = "server-inventory-quantity-stacking-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerInventoryQuantityStackingMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "inventory-events-mod", "server-inventory-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
item-quantity-meta = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-quantity-operations-lib = { git = "https://github.com/paolobettelini/modularis.git" }
server-inventory-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
