[package]
name = "server-chunk-residency-player-interest-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-residency-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
