[package]
name = "server-player-movement-collision-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
block-manager-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-shape-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-block-collision-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
