[package]
name = "client-sun-directional-light-bevy-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientSunDirectionalLightBevyMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "client-sun-api", "client-game-state-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-sun-api = { path = "../client-sun-api" }
sun-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }

