[package]
name = "server-biome-birch-forest-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerBiomeBirchForestVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-biome-api",
    "biome-birch-forest",
    "server-biome-feature-caves-vanilla-mod",
    "server-biome-feature-ores-vanilla-mod",
    "server-biome-feature-birch-trees-vanilla-mod",
]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
biome-birch-forest = { path = "../biome-birch-forest" }
generated-biome-registry = "0.1.0"
generated-block-registry = "0.1.0"
server-biome-api = { path = "../server-biome-api" }
server-biome-feature-caves-vanilla-mod = { path = "../server-biome-feature-caves-vanilla-mod" }
server-biome-feature-ores-vanilla-mod = { path = "../server-biome-feature-ores-vanilla-mod" }
server-biome-feature-birch-trees-vanilla-mod = { path = "../server-biome-feature-birch-trees-vanilla-mod" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-biome-registry = { path = "../generated-biome-registry" }
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
