[package]
name = "client-grass-settings-generated-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientGrassSettingsGeneratedImpl"
provides = "client-grass-settings-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "client-settings-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-grass-settings-api = { path = "../client-grass-settings-api" }
client-settings-api = { path = "../client-settings-api" }
generated-client-settings-registry = "0.1.0"
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-client-settings-registry = { path = "../generated-client-settings-registry" }
