[package]
name = "client-player-flight-speed-network-receive-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerFlightSpeedNetworkReceiveMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "player-flight-speed-api", "network-protocol-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
network-protocol-mod = { git = "https://github.com/paolobettelini/modularis.git" }
player-flight-speed-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
