[package]
name = "block-edit-events-api"
version = "0.1.2"
edition = "2024"

[dependencies]
voxel-frame-api = { git = "https://github.com/paolobettelini/modularis.git" }
bevy = "0.17.3"
block-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-state = { path = "../generated-block-state" }
generated-block-registry = { path = "../generated-block-registry" }
