[package]
name = "block-shape-api"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
block-instance-api = { path = "../block-instance-api" }
collision-api = { path = "../collision-api" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
