[package]
name = "server-block-edit-network-send-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerBlockEditNetworkSendMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "block-edit-events-mod",
    "server-network-events-api",
    "server-chunk-world-api",
    "server-player-registry-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-network-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
