[package]
name = "server-command-speed-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerCommandSpeedVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-command-api",
    "server-chat-api",
    "server-player-registry-api",
    "server-player-speed-api",
]
run = []
ownership = []

[dependencies]
audience-api = { git = "https://github.com/paolobettelini/modularis.git" }
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chat-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-command-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-speed-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
