[package]
name = "client-session-network-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ClientSessionNetworkMod"
provides = "client-session-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-network-api",
    "client-game-state-api",
    "network-protocol-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-network-api = { path = "../client-network-api" }
client-session-api = { path = "../client-session-api" }
generated-network-messages = "0.1.0"
network-protocol-mod = { path = "../network-protocol-mod" }
patchwork-game-auth-api = { path = "../patchwork-game-auth-api" }
session-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
