[package]
name = "client-inventory-ui-bevy-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientInventoryUiBevyMod"
provides = "client-inventory-ui-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-game-state-api",
    "client-inventory-cache-api",
    "inventory-events-mod",
    "item-manager-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
client-game-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-inventory-cache-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-inventory-ui-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
item-manager-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
