[package]
name = "client-chunk-cache-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
support = true

[dependencies]
bevy = "0.17.3"
block-instance-api = { path = "../block-instance-api" }
chunk-api = { path = "../chunk-api" }
voxel-math-api = { path = "../voxel-math-api" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
