[package]
name = "server-game-bootstrap-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerGameBootstrapMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-bevy-runner-mod"]
run = []
ownership = ["bevy-mod"]

[dependencies]
bevy-mod = { path = "../bevy-mod" }
server-bevy-runner-mod = { path = "../server-bevy-runner-mod" }
tokio = { version = "1.48.0", features = ["full"] }
