[package]
name = "client-inventory-cache-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientInventoryCacheMod"
provides = "client-inventory-cache-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "inventory-events-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
client-inventory-cache-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
