[package]
name = "client-pause-disconnect-menu-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ClientPauseDisconnectMenuMod"

[package.metadata.mod.dependencies]
init = ["client-menu-api", "client-game-state-api", "client-pause-menu-mod"]
run = []
ownership = []

[dependencies]
client-game-state-api = { path = "../client-game-state-api" }
client-menu-api = { path = "../client-menu-api" }
client-pause-menu-mod = { path = "../client-pause-menu-mod" }
tokio = { version = "1.48.0", features = ["full"] }
