[package]
name = "server-player-visibility-scope-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerVisibilityScopeImpl"
provides = "server-player-visibility-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-scope-api"]
run = []
ownership = []

[dependencies]
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-visibility-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-scope-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
