[package]
name = "server-chunk-world-api"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
block-instance-api = { path = "../block-instance-api" }
chunk-api = { path = "../chunk-api" }
player-network-message-types = { path = "../player-network-message-types" }
server-chunk-provider-api = { path = "../server-chunk-provider-api" }
voxel-math-api = { path = "../voxel-math-api" }
world-instance-api = { path = "../world-instance-api" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
