[package]
name = "server-chunk-world-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
support = true

[dependencies]
bevy = "0.17.3"
block-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
chunk-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-provider-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
