[package]
name = "server-player-game-mode-vanilla-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerGameModeVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "server-player-game-mode-api",
    "server-player-permission-api",
    "server-player-outline-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
server-player-game-mode-api = { path = "../server-player-game-mode-api" }
server-player-game-mode-vanilla-lib = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-outline-api = { path = "../server-player-outline-api" }
server-player-permission-api = { path = "../server-player-permission-api" }
tokio = { version = "1.48.0", features = ["full"] }
