[package]
name = "client-grass-tint-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientGrassTintVanillaMod"
provides = "client-grass-tint-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "block-grass",
    "block-moss",
    "block-netherrack",
    "block-crimson-nylium",
    "block-warped-nylium",
    "block-soul-sand",
    "block-basalt",
    "block-calcite",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
block-basalt = { path = "../block-basalt" }
block-calcite = { path = "../block-calcite" }
block-crimson-nylium = { path = "../block-crimson-nylium" }
block-grass = { path = "../block-grass" }
block-moss = { path = "../block-moss" }
block-netherrack = { path = "../block-netherrack" }
block-soul-sand = { path = "../block-soul-sand" }
block-warped-nylium = { path = "../block-warped-nylium" }
client-dimension-api = { path = "../client-dimension-api" }
client-grass-tint-api = { path = "../client-grass-tint-api" }
generated-block-registry = "0.1.0"
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
