[package]
name = "server-place-block-item-use-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlaceBlockItemUseMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "inventory-events-mod",
    "block-edit-events-mod",
    "server-chunk-world-api",
    "server-player-registry-api",
    "server-player-gravity-api",
    "server-player-hitbox-api",
    "server-block-interaction-rules-api",
    "block-manager-api",
    "block-shape-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-edit-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
block-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-manager-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-shape-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-mod = { git = "https://github.com/paolobettelini/modularis.git" }
item-place-block-meta = { git = "https://github.com/paolobettelini/modularis.git" }
item-use-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-place-block-item-use-lib = { git = "https://github.com/paolobettelini/modularis.git" }
server-block-interaction-rules-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
