[package]
name = "server-chunk-storage-periodic-flush-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerChunkStoragePeriodicFlushMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-bevy-runner-mod", "server-chunk-storage-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
server-bevy-runner-mod = { path = "../server-bevy-runner-mod" }
server-chunk-storage-api = { path = "../server-chunk-storage-api" }
tokio = { version = "1.48.0", features = ["full"] }
