[package]
name = "server-portal-travel-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
generated-block-registry = "0.1.0"
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
portal-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-dimension-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-portal-api = { git = "https://github.com/paolobettelini/modularis.git" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
