[package]
name = "client-block-interaction-raycast-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientBlockInteractionRaycastMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "block-edit-events-mod",
    "client-block-interaction-events-mod",
    "block-manager-api",
    "client-input-api",
    "client-camera-api",
    "client-chunk-cache-api",
    "block-shape-api",
    "client-game-state-api",
    "client-block-interaction-rules-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
block-edit-events-api = { path = "../block-edit-events-api" }
block-edit-events-mod = { path = "../block-edit-events-mod" }
block-manager-api = { path = "../block-manager-api" }
block-shape-api = { path = "../block-shape-api" }
client-block-interaction-events-api = { path = "../client-block-interaction-events-api" }
client-block-interaction-events-mod = { path = "../client-block-interaction-events-mod" }
client-block-interaction-rules-api = { path = "../client-block-interaction-rules-api" }
client-camera-api = { path = "../client-camera-api" }
client-chunk-cache-api = { path = "../client-chunk-cache-api" }
client-game-state-api = { path = "../client-game-state-api" }
client-input-api = { path = "../client-input-api" }
item-use-api = { path = "../item-use-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-raycast-api = { path = "../voxel-raycast-api" }
