[package]
name = "item-diamond-ore-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemDiamondOreBlockMod"

[package.metadata.mod.dependencies]
init = ["block-diamond-ore"]
run = []
ownership = []

[package.metadata.item]
id = "demo:diamond_ore_block"
label = "Diamond Ore"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-diamond-ore = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
