[package]
name = "server-biome-feature-caves-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerBiomeFeatureCavesVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-biome-api"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
coherent-noise-api = { path = "../coherent-noise-api" }
generated-block-registry = "0.1.0"
server-biome-api = { path = "../server-biome-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { path = "../voxel-math-api" }

[patch.crates-io]
generated-biome-registry = { path = "../generated-biome-registry" }
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
