[package]
name = "item-deepslate-tiles-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemDeepslateTilesBlockMod"

[package.metadata.mod.dependencies]
init = ["block-deepslate-tiles"]
run = []
ownership = []

[package.metadata.item]
id = "demo:deepslate_tiles_block"
label = "Deepslate Tiles"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-deepslate-tiles = { path = "../block-deepslate-tiles" }
tokio = { version = "1.48.0", features = ["full"] }
