[package]
name = "client-setting-mouse-sensitivity"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "SettingMouseSensitivityMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.setting]
id = "controls.mouse_sensitivity"
label = "Mouse sensitivity"
type = "f32"
input = "f32"
default = 0.15
min = 0.01
max = 2.0
section = "controls"
section_label = "Controls"

[dependencies]
settings-schema-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
