[package]
name = "item-chiseled-stone-bricks-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemChiseledStoneBricksBlockMod"

[package.metadata.mod.dependencies]
init = ["block-chiseled-stone-bricks"]
run = []
ownership = []

[package.metadata.item]
id = "demo:chiseled_stone_bricks_block"
label = "Chiseled Stone Bricks"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-chiseled-stone-bricks = { path = "../block-chiseled-stone-bricks" }
tokio = { version = "1.48.0", features = ["full"] }
