[package]
name = "client-chunk-render-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
api = true

[dependencies]
bevy = "0.17.3"
chunk-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-chunk-mesh-api = { path = "../client-chunk-mesh-api" }
client-chunk-streaming-api = { path = "../client-chunk-streaming-api" }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }
