[package]
name = "server-player-jump-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerPlayerJumpVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "block-manager-api",
    "server-chunk-world-api",
    "server-player-registry-api",
    "server-player-gravity-api",
    "server-player-hitbox-api",
    "block-shape-api",
    "network-protocol-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
block-manager-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-shape-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
player-block-collision-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-jump-lib = { git = "https://github.com/paolobettelini/modularis.git" }
player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-jump-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-player-registry-api = { git = "https://github.com/paolobettelini/modularis.git" }
network-protocol-mod = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
