[package]
name = "client-item-catalog-creative-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ClientItemCatalogCreativeMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-inventory-ui-api",
    "client-inventory-cache-api",
    "client-player-permission-api",
    "creative-inventory-events-mod",
    "client-game-state-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-game-state-api = { path = "../client-game-state-api" }
client-inventory-cache-api = { path = "../client-inventory-cache-api" }
client-inventory-ui-api = { path = "../client-inventory-ui-api" }
client-player-permission-api = { path = "../client-player-permission-api" }
creative-inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
creative-inventory-events-mod = { path = "../creative-inventory-events-mod" }
generated-permission-registry = "0.1.0"
inventory-core-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-permission-registry = { path = "../generated-permission-registry" }
