[package]
name = "server-inventory-network-sync-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerInventoryNetworkSyncMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "inventory-events-mod",
    "server-network-events-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
generated-network-messages = "0.1.0"
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-mod = { path = "../inventory-events-mod" }
inventory-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
server-network-events-api = { path = "../server-network-events-api" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
