[package]
name = "item-manager-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
support = true

[dependencies]
generated-item-registry = "0.1.0"
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-item-registry = { path = "../generated-item-registry" }
