[package]
name = "player-scale-network-messages-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "PlayerScaleNetworkMessagesMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.network.messages]
clientbound = ["player_scale_network_message_types::PlayerScaleChanged"]
serverbound = []

[dependencies]
player-scale-network-message-types = { path = "../player-scale-network-message-types" }
tokio = { version = "1.48.0", features = ["full"] }
