[package]
name = "server-player-world-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
api = true

[dependencies]
bevy = "0.17.3"
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
