[package]
name = "client-cell-menu-drag-drop-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientCellMenuDragDropMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "cell-menu-events-mod",
    "client-cell-menu-ui-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
cell-menu-api = { path = "../cell-menu-api" }
cell-menu-events-mod = { path = "../cell-menu-events-mod" }
client-cell-menu-ui-api = { path = "../client-cell-menu-ui-api" }
tokio = { version = "1.48.0", features = ["full"] }
