[package]
name = "item-purpur-pillar-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemPurpurPillarBlockMod"

[package.metadata.mod.dependencies]
init = ["block-purpur-pillar"]
run = []
ownership = []

[package.metadata.item]
id = "demo:purpur_pillar_block"
label = "Purpur Pillar"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-purpur-pillar = { path = "../block-purpur-pillar" }
tokio = { version = "1.48.0", features = ["full"] }
