[package]
name = "server-portal-ignite-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
block-manager-api = { git = "https://github.com/paolobettelini/modularis.git" }
inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-use-api = { git = "https://github.com/paolobettelini/modularis.git" }
portal-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-world-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-dimension-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-portal-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-item-metadata = { path = "../generated-item-metadata" }
generated-item-registry = { path = "../generated-item-registry" }
