[package]
name = "server-player-jump-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
block-manager-api = { path = "../block-manager-api" }
block-shape-api = { path = "../block-shape-api" }
player-block-collision-api = { path = "../player-block-collision-api" }
player-gravity-api = { path = "../player-gravity-api" }
player-hitbox-api = { path = "../player-hitbox-api" }
player-jump-api = { path = "../player-jump-api" }
player-network-message-types = { path = "../player-network-message-types" }
server-chunk-world-api = { path = "../server-chunk-world-api" }
