[package]
name = "item-tinted-glass-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemTintedGlassBlockMod"

[package.metadata.mod.dependencies]
init = ["block-tinted-glass"]
run = []
ownership = []

[package.metadata.item]
id = "demo:tinted_glass_block"
label = "Tinted Glass"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-tinted-glass = { path = "../block-tinted-glass" }
tokio = { version = "1.48.0", features = ["full"] }
