[package]
name = "server-biome-feature-short-grass-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerBiomeFeatureShortGrassVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-biome-api", "block-short-grass"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
block-short-grass = { path = "../block-short-grass" }
generated-block-registry = "0.1.0"
server-biome-api = { path = "../server-biome-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-biome-registry = { path = "../generated-biome-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
