[package]
name = "chunk-section-api"
version = "0.1.0"
edition = "2024"

[dependencies]
block-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
packed-bit-array-api = { git = "https://github.com/paolobettelini/modularis.git" }
serde = { version = "1.0", features = ["derive"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
