[package]
name = "item-deepslate-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemDeepslateBlockMod"

[package.metadata.mod.dependencies]
init = ["block-deepslate"]
run = []
ownership = []

[package.metadata.item]
id = "demo:deepslate_block"
label = "Deepslate"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-deepslate = { path = "../block-deepslate" }
tokio = { version = "1.48.0", features = ["full"] }
