[package]
name = "server-command-spawn-frame-lib"
version = "0.1.1"
edition = "2024"

[dependencies]
bevy = "0.17.3"
server-command-api = { path="../server-command-api" }
server-chat-api = { path="../server-chat-api" }
server-chunk-world-api = { path="../server-chunk-world-api" }
server-chunk-provider-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-voxel-frame-spawn-lib = { git = "https://github.com/paolobettelini/modularis.git" }
block-state-api = { git = "https://github.com/paolobettelini/modularis.git" }
audience-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-permission-registry = "0.1.0"
