[package]
name = "client-player-dimension-position-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerDimensionPositionMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "client-dimension-api", "client-player-controller-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-dimension-api = { path = "../client-dimension-api" }
client-player-controller-api = { path = "../client-player-controller-api" }
tokio = { version = "1.48.0", features = ["full"] }
