[package]
name = "item-calcite-block"
version = "0.1.0"
edition = "2024"
[package.metadata.mod]
entry = "ItemCalciteBlockMod"
[package.metadata.mod.dependencies]
init = ["block-calcite"]
run = []
ownership = []
[package.metadata.item]
id = "demo:calcite_block"
label = "Calcite"
[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-calcite = { path = "../block-calcite" }
tokio = { version = "1.48.0", features = ["full"] }
