[package]
name = "item-gilded-blackstone-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemGildedBlackstoneBlockMod"

[package.metadata.mod.dependencies]
init = ["block-gilded-blackstone"]
run = []
ownership = []

[package.metadata.item]
id = "demo:gilded_blackstone_block"
label = "Gilded Blackstone"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-gilded-blackstone = { path = "../block-gilded-blackstone" }
tokio = { version = "1.48.0", features = ["full"] }
