[package]
name = "server-entity-network-sync-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerEntityNetworkSyncMod"
[package.metadata.mod.dependencies]
init = ["bevy-mod","server-entity-state-mod","server-network-events-api","server-player-registry-api"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = {path="../bevy-mod"}
server-entity-state-mod = {path="../server-entity-state-mod"}
server-entity-api = {path="../server-entity-api"}
server-entity-visibility-api = {path="../server-entity-visibility-api"}
server-network-events-api = {path="../server-network-events-api"}
server-player-registry-api = {path="../server-player-registry-api"}
entity-state-api = {path="../entity-state-api"}
entity-network-message-types = {path="../entity-network-message-types"}
generated-network-messages = "0.1.0"
tokio = {version="1",features=["full"]}
