[package]
name = "server-biome-feature-dripstone-spires-vanilla-mod"
version = "0.1.2"
edition = "2024"

[package.metadata.mod]
entry = "ServerBiomeFeatureDripstoneSpiresVanillaMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "server-biome-api", "block-dripstone-block", "block-tuff", "block-cobbled-deepslate"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
block-cobbled-deepslate = { path = "../block-cobbled-deepslate" }
block-tuff = { path = "../block-tuff" }
block-dripstone-block = { path = "../block-dripstone-block" }
generated-block-registry = "0.1.0"
server-biome-api = { path = "../server-biome-api" }
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-biome-registry = { path = "../generated-biome-registry" }
generated-block-state = { path = "../generated-block-state" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
