[package]
name = "item-crimson-nylium-block"
version = "0.1.0"
edition = "2024"
[package.metadata.mod]
entry = "ItemCrimsonNyliumBlockMod"
[package.metadata.mod.dependencies]
init = ["block-crimson-nylium"]
run = []
ownership = []
[package.metadata.item]
id = "demo:crimson_nylium_block"
label = "Crimson Nylium"
[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-crimson-nylium = { path = "../block-crimson-nylium" }
tokio = { version = "1.48.0", features = ["full"] }
