[package]
name = "item-yellow-glazed-terracotta-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemYellowGlazedTerracottaBlockMod"

[package.metadata.mod.dependencies]
init = ["block-yellow-glazed-terracotta"]
run = []
ownership = []

[package.metadata.item]
id = "demo:yellow_glazed_terracotta_block"
label = "Yellow Glazed Terracotta"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-yellow-glazed-terracotta = { path = "../block-yellow-glazed-terracotta" }
tokio = { version = "1.48.0", features = ["full"] }
