[package]
name = "server-chunk-routing-single-world-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerChunkRoutingSingleWorldMod"
provides = "server-chunk-routing-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
server-chunk-provider-api = { git = "https://github.com/paolobettelini/modularis.git" }
server-chunk-routing-api = { path = "../server-chunk-routing-api" }
tokio = { version = "1.48.0", features = ["full"] }
world-instance-api = { git = "https://github.com/paolobettelini/modularis.git" }
