[package]
name = "item-cyan-terracotta-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemCyanTerracottaBlockMod"

[package.metadata.mod.dependencies]
init = ["block-cyan-terracotta"]
run = []
ownership = []

[package.metadata.item]
id = "demo:cyan_terracotta_block"
label = "Cyan Terracotta"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-cyan-terracotta = { path = "../block-cyan-terracotta" }
tokio = { version = "1.48.0", features = ["full"] }
