[package]
name = "client-setting-grass-blade-height"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientSettingGrassBladeHeightMod"

[package.metadata.mod.dependencies]
init = []
run = []
ownership = []

[package.metadata.setting]
id = "grass.blade_height"
label = "Blade height"
type = "f32"
input = "f32"
default = 0.44
min = 0.05
max = 1.5
section = "graphics/grass"
section_label = "Grass"

[dependencies]
settings-schema-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
