[package]
name = "client-grass-mesh-fabric-style-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientGrassMeshFabricStyleImpl"
provides = "client-grass-mesh-api"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-grass-settings-api",
    "client-grass-tint-api",
    "block-short-grass",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
block-short-grass = { git = "https://github.com/paolobettelini/modularis.git" }
chunk-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-dimension-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-grass-mesh-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-grass-settings-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-grass-tint-api = { git = "https://github.com/paolobettelini/modularis.git" }
generated-block-registry = "0.1.0"
tokio = { version = "1.48.0", features = ["full"] }
voxel-math-api = { git = "https://github.com/paolobettelini/modularis.git" }

[patch.crates-io]
generated-block-metadata = { path = "../generated-block-metadata" }
generated-block-registry = { path = "../generated-block-registry" }
generated-dimension-registry = { path = "../generated-dimension-registry" }
