[package]
name = "client-creative-inventory-network-send-mod"
version = "0.1.1"
edition = "2024"

[package.metadata.mod]
entry = "ClientCreativeInventoryNetworkSendMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod", "creative-inventory-events-mod", "client-network-api", "network-protocol-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-network-api = { path = "../client-network-api" }
creative-inventory-events-api = { git = "https://github.com/paolobettelini/modularis.git" }
creative-inventory-events-mod = { path = "../creative-inventory-events-mod" }
creative-inventory-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
network-protocol-mod = { path = "../network-protocol-mod" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
