[package]
name = "item-honeycomb-block"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ItemHoneycombBlockMod"

[package.metadata.mod.dependencies]
init = ["block-honeycomb-block"]
run = []
ownership = []

[package.metadata.item]
id = "demo:honeycomb_block"
label = "Honeycomb Block"

[dependencies]
item-api = { git = "https://github.com/paolobettelini/modularis.git" }
item-render-api = { git = "https://github.com/paolobettelini/modularis.git" }
block-honeycomb-block = { path = "../block-honeycomb-block" }
tokio = { version = "1.48.0", features = ["full"] }
