[package]
name = "server-entity-state-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerEntityStateMod"
[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = {path="../bevy-mod"}
server-entity-api = {path="../server-entity-api"}
entity-state-api = {path="../entity-state-api"}
tokio = {version="1",features=["full"]}
