[package]
name = "client-grass-player-contact-vanilla-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientGrassPlayerContactVanillaMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "client-grass-interaction-api",
    "client-player-controller-api",
    "player-gravity-api",
    "player-hitbox-api",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
client-grass-interaction-api = { git = "https://github.com/paolobettelini/modularis.git" }
client-player-controller-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-gravity-api = { git = "https://github.com/paolobettelini/modularis.git" }
player-hitbox-api = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }
