[package]
name = "server-network-events-api"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerNetworkEventsApiMod"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { git = "https://github.com/paolobettelini/modularis.git" }
generated-network-messages = "0.1.0"
player-network-message-types = { git = "https://github.com/paolobettelini/modularis.git" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
