[package]
name = "client-player-gravity-network-receive-mod"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ClientPlayerGravityNetworkReceiveMod"

[package.metadata.mod.dependencies]
init = [
    "bevy-mod",
    "player-gravity-api",
    "client-player-gravity-map-api",
    "client-session-api",
    "network-protocol-mod",
]
run = []
ownership = []

[dependencies]
bevy = "0.17.3"
bevy-mod = { path = "../bevy-mod" }
client-player-gravity-map-api = { path = "../client-player-gravity-map-api" }
client-session-api = { path = "../client-session-api" }
generated-network-messages = "0.1.0"
network-protocol-mod = { path = "../network-protocol-mod" }
player-gravity-api = { path = "../player-gravity-api" }
tokio = { version = "1.48.0", features = ["full"] }

[patch.crates-io]
generated-network-messages = { path = "../generated-network-messages" }
