[package]
name = "server-tick-rate-20hz-default-impl"
version = "0.1.0"
edition = "2024"

[package.metadata.mod]
entry = "ServerTickRate20HzDefaultImpl"
provides = "server-tick-api"

[package.metadata.mod.dependencies]
init = ["bevy-mod"]
run = []
ownership = []

[dependencies]
bevy-mod = { path = "../bevy-mod" }
server-tick-api = { path = "../server-tick-api" }
tokio = { version = "1.48.0", features = ["full"] }
